config/routes.rb
TrelloGithubHooks::Application.routes.draw do
  devise_for :users

  resources :boards

  resources :repositories

  resources :users do
    get 'token' => 'users#edit_token'
    patch 'token' => 'users#update_token'
  end

  post 'push' => 'boards#push'

  get 'profile' => 'users#profile'
  get 'profile/edit' => 'users#edit_profile'

  

  root :to => 'application#index'
end

app/models/repository.rb
# == Schema Information
# Schema version: 20131001071632
#
# Table name: repositories
#
# *id*::         <tt>integer, not null, primary key</tt>
# *name*::       <tt>string(255)</tt>
# *user_id*::    <tt>integer, indexed</tt>
# *created_at*:: <tt>datetime</tt>
# *updated_at*:: <tt>datetime</tt>
#
# Indexes
#
#  index_repositories_on_user_id  (user_id)
#--
# == Schema Information End
#++

class Repository < ActiveRecord::Base
  belongs_to :user
  has_many :boards

  validates :name,
            presence: true,
            uniqueness: true
  validates :user,
            presence: true
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_action :set_repository, only: [:show, :edit, :update, :destroy]
  before_action :set_user

  # GET /repositories
  # GET /repositories.json
  def index
    @repositories = Repository.all.select { |repo| can? :view, repo }
  end

  # GET /repositories/1
  # GET /repositories/1.json
  def show
    access_denied! 'cannot.view.repository', repositories_path if cannot? :view, @repository
  end

  # GET /repositories/new
  def new
    access_denied! 'cannot.create.repository', repositories_path if cannot? :create, Repository
    @repository = Repository.new
  end

  # GET /repositories/1/edit
  def edit
    access_denied! 'cannot.edit.repository', repositories_path if cannot? :edit, @repository
  end

  # POST /repositories
  # POST /repositories.json
  def create
    access_denied! 'cannot.create.repository', repositories_path if cannot? :create, Repository

    @repository = Repository.new(repository_params)
    access_denied! 'cannot.edit.repository', repositories_path if cannot? :edit, @repository

    respond_to do |format|
      if @repository.save
        format.html { redirect_to @repository, notice: 'Repository was successfully created.' }
        format.json { render action: 'show', status: :created, location: @repository }
      else
        format.html { render action: 'new' }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repositories/1
  # PATCH/PUT /repositories/1.json
  def update
    access_denied! 'cannot.edit.repository', repositories_path if cannot? :edit, @repository

    respond_to do |format|
      if @repository.update(repository_params)
        format.html { redirect_to @repository, notice: 'Repository was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repositories/1
  # DELETE /repositories/1.json
  def destroy
    access_denied! 'cannot.delete.repository', repositories_path if cannot? :delete, @repository

    @repository.destroy
    respond_to do |format|
      format.html { redirect_to repositories_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_repository
    @repository = Repository.find(params[:id])
  end

  def set_user
    @user = current_user
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def repository_params
    params.require(:repository).permit(:name, :user_id)
  end
end

app/views/repositories/_form.html.slim
= simple_form_for(@repository, html: {class: 'form-horizontal'}) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :user_id, as: :hidden, input_html: {value: @user.id}

  .form-actions
    = f.button :submit

app/views/repositories/edit.html.slim
h1 Editing repository

== render 'form'

= link_to 'Show', @repository
'|
= link_to 'Back', repositories_path

app/views/repositories/index.html.slim
h1 Listing repositories

table.table
  tr
    th Name
    th User
    th
    th
    th

  - @repositories.each do |repository|
    tr
      td = link_to repository.name, "https://github.com/#{repository.name}"
      td = link_to repository.user.try(:email), user_path(repository.user)
      td = link_to 'Show', repository
      td
        - if can? :edit, repository
          = link_to 'Edit', edit_repository_path(repository)
      td
        - if can? :delete, repository
          = link_to 'Destroy', repository, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Repository', new_repository_path

app/views/repositories/new.html.slim
h1 New repository

== render 'form'

= link_to 'Back', repositories_path

app/views/repositories/show.html.slim
p#notice = notice

p
  strong Name:
  = @repository.name
p
  strong User:
  = @repository.user.try(:email)

= link_to 'Edit', edit_repository_path(@repository)
'|
= link_to 'Back', repositories_path