config/routes.rb
TrelloGithubHooks::Application.routes.draw do
  devise_for :users

  resources :boards

  resources :repositories

  resources :users do
    get 'token' => 'users#edit_token'
    patch 'token' => 'users#update_token'
  end

  post 'push' => 'boards#push'

  get 'profile' => 'users#profile'
  get 'profile/edit' => 'users#edit_profile'

  

  root :to => 'application#index'
end

app/models/user.rb
# == Schema Information
# Schema version: 20130930155414
#
# Table name: users
#
# *id*::                     <tt>integer, not null, primary key</tt>
# *email*::                  <tt>string(255), default(""), not null, indexed</tt>
# *encrypted_password*::     <tt>string(255), default(""), not null</tt>
# *reset_password_token*::   <tt>string(255), indexed</tt>
# *reset_password_sent_at*:: <tt>datetime</tt>
# *remember_created_at*::    <tt>datetime</tt>
# *sign_in_count*::          <tt>integer, default(0), not null</tt>
# *current_sign_in_at*::     <tt>datetime</tt>
# *last_sign_in_at*::        <tt>datetime</tt>
# *current_sign_in_ip*::     <tt>string(255)</tt>
# *last_sign_in_ip*::        <tt>string(255)</tt>
# *created_at*::             <tt>datetime</tt>
# *updated_at*::             <tt>datetime</tt>
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#--
# == Schema Information End
#++

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :repositories

  def setup?
    not self.trello_token.nil?
  end

  def name
    self.email
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all.select {|user| can? :view, user}
  end

  # GET /users/1
  # GET /users/1.json
  def show
    access_denied! 'cannot.view.user', users_path if cannot? :edit, @user
  end

  # GET /users/1/edit
  def edit
    access_denied! 'cannot.edit.user', users_path if cannot? :edit, @user
  end

  # GET /users/1/edit
  def edit_token
    @user = User.find(params[:user_id])
    access_denied! 'cannot.edit.user', users_path if cannot? :edit, @user

    @user.trello_token = params[:token] unless params[:token].blank?
    redirect_to @user, notice: 'Fill up API key first!' if @user.trello_api_key.blank?
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    access_denied! 'cannot.edit.user', users_path if cannot? :edit, @user

    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1/token
  # PATCH/PUT /users/1/token.json
  def update_token
    @user = User.find(params[:user_id])
    access_denied! 'cannot.edit.user', users_path if cannot? :edit, @user

    respond_to do |format|
      if @user.update(params.require(:user).permit(:trello_token))
        format.html { redirect_to @user, notice: 'Token was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit_token' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    access_denied! 'cannot.delete.user', users_path if cannot? :edit, @user

    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def profile
    @user = current_user
    access_denied! 'cannot.view.user', users_path if cannot? :edit, @user

    render :show
  end

  def edit_profile
    @user = current_user
    access_denied! 'cannot.edit.user', profile_path if cannot? :edit, @user

    render :edit
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :trello_api_key)
    end
end

app/views/users/_form.html.slim
= simple_form_for(@user, html: {class: 'form-horizontal'}) do |f|
  = f.error_notification

  .form-inputs
    = f.input :email
    = f.input :trello_api_key
    = link_to 'Request API Key', 'https://trello.com/1/appKey/generate', target: '_blank'

  .form-actions
    = f.button :submit

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

= link_to 'Show', @user
'|
- unless @user.trello_api_key.blank?
  = link_to 'Edit Token', user_token_path(@user)
  '|
= link_to 'Back', users_path

app/views/users/edit_token.html.slim
h1 Editing user token

= simple_form_for(@user, url: user_token_path(@user), html: {method: :patch, class: 'form-horizontal'}) do |f|
  = f.error_notification

  .form-inputs
    = f.input :trello_token

  .form-actions
    = f.button :submit

= link_to 'Show', @user
'|
= link_to 'Edit', edit_user_path(@user)
'|
= link_to 'Back', users_path


= content_for :js
  coffee:
    jQuery ->
      fragment = document.location.hash.split('#token=')
      if fragment.length > 1
        console.log fragment[1]
        $('#user_trello_token').attr('value', fragment[1])

app/views/users/index.html.slim
h1 Listing users

table.table
  tr
    th Email
    th API key
    th token
    th
    th
    th

  - @users.each do |user|
    tr
      td= user.email
      td= user.trello_api_key
      td
        - if not user.setup?
          - if user.trello_api_key.blank?
            'fill api key first
          - else
            = link_to 'Request Token', "https://trello.com/1/authorize?key=#{user.trello_api_key}&name=Trello+Github+Hooks&expiration=never&response_type=token&scope=read,write&callback_method=fragment&return_url=#{user_token_url(user)}".html_safe
        - else
          'set
      td
        - if can? :view, user
          = link_to 'Show', user
      td
        - if can? :edit, user
          = link_to 'Edit', edit_user_path(user)
      td
        - if can? :delete, user
          = link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Member', new_user_path

app/views/users/show.html.slim
p#notice = notice

p
  strong Email:
  '
  = @user.email
p
  strong Trello Key:
  '
  = @user.trello_api_key
p
  strong Trello Token:
  '
  - if not @user.setup?
    - if @user.trello_api_key.blank?
      'fill api key first
    - else
      = link_to 'Request Token', "https://trello.com/1/authorize?key=#{@user.trello_api_key}&name=Trello+Github+Hooks&expiration=never&response_type=token&scope=read,write&callback_method=fragment&return_url=#{user_token_url(@user)}".html_safe
  - else
    = @user.trello_token

= link_to 'Edit', edit_user_path(@user)
'|
- unless @user.trello_api_key.blank?
  = link_to 'Edit Token', user_token_path(@user)
  '|
= link_to 'Back', users_path          

- if @user.setup?
  h3 Demo
  p
    = link_to 'Get the member’s record:', "https://trello.com/1/members/me?key=#{@user.trello_api_key}&token=#{@user.trello_token}"
  p
    = link_to 'Get the cards that a user is assigned to', "https://trello.com/1/members/my/cards?key=#{@user.trello_api_key}&token=#{@user.trello_token}"
  p
    = link_to 'Get the open boards that a user is a member of', "https://trello.com/1/members/my/boards?key=#{@user.trello_api_key}&token=#{@user.trello_token}"
  p
    = link_to 'Get the boards that a user has pinned to their boards menu:', "https://trello.com/1/members/my/boards/pinned?key=#{@user.trello_api_key}&token=#{@user.trello_token}"
  p
    = link_to 'Get the organizations that a user is a member of', "https://trello.com/1/members/my/organizations?key=#{@user.trello_api_key}&token=#{@user.trello_token}"