config/routes.rb
TrelloGithubHooks::Application.routes.draw do
  devise_for :users

  resources :boards

  resources :repositories

  resources :users do
    get 'token' => 'users#edit_token'
    patch 'token' => 'users#update_token'
  end

  post 'push' => 'boards#push'

  get 'profile' => 'users#profile'
  get 'profile/edit' => 'users#edit_profile'

  

  root :to => 'application#index'
end

app/views/layouts/application.html.slim
doctype 5
html
  head
    title Trello Github Hooks
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag    'application-css', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

    = csrf_meta_tag
  body id=(controller.controller_name) class=(controller.action_name)
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        .container
          button.btn.btn-navbar[type="button" data-toggle="collapse" data-target=".nav-collapse"]
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.brand[href="#"]
            | Trello Github Hooks
          .nav-collapse.collapse
            ul.nav
              li= nav_link_to 'Dashboard', root_path
              li= nav_link_to 'Users', users_path
              li= nav_link_to 'Boards', boards_path
              li= nav_link_to 'Repositories', repositories_path
            form.navbar-form.pull-right
              ul.nav
                - if current_user
                  li.dropdown
                    a.dropdown-toggle[href="#" data-toggle="dropdown"]
                      = current_user.email
                      b.caret
                    ul.dropdown-menu
                      li= nav_link_to('Profile', profile_path)
                      li.divider
                      li= nav_link_to('Change password', edit_user_registration_path)
                      li= link_to 'Sign Out', destroy_user_session_path, method: :delete
                - else
                  li= link_to 'Sign In', new_user_session_path
 
    .wrapper
      - flash.each do |name, msg|
        = content_tag :div, raw(msg), class: "alert #{alert_class(name)}"
 
      = yield
 
    .push
 
    footer
      .container
        p &copy; 2013 All rights reserved.
        p
          a[href='#'] Michał Knapik
 
 
  = yield :js